[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "mrov"
name = "AutoScroll"
description = "A mod for enabling auto-scrolling of ship screen's text."
websiteUrl = "https://github.com/AndreyMrovol/LethalAutoScroll"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "../icon.png"
readme = "../README.md"
outdir = "../AutoScroll/dist"

[[build.copy]]
source = "../AutoScroll/bin/Release/netstandard2.1/AutoScroll.dll"
target = "/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../LICENSE.md"
target = "/"

[publish]
communities = [ "lethal-company", ]